feat: checkbox styles improvement
BitcreditProtocol/E-Bill-frontend pull request #53
Opened 2024-11-15 15:58 UTC by nafisreza

Fixes #50

Improvements:
[x] The component styling must match all the states specified in the design specs: default, hover and disabled
[x] The component must have two different sizes, as per the design specs: small (sm) and medium (md)
[x] There has to be a property to set the checkbox state (checked or unchecked)
[x] There has to be a property to set the checkbox size (sm or md)
[x] There has to be a property to turn the checkbox into the disabled state

2024-11-16 02:28 UTC, cryptosalomao commented on src/components/ui/checkbox.tsx
> +import { cva, type VariantProps } from "class-variance-authority"
`type VariantProps` is unused.

2024-11-16 02:30 UTC, cryptosalomao commented on src/components/ui/checkbox.tsx
> +      "disabled:!bg-[#D1CCC1] disabled:!border-0 disabled:cursor-not-allowed"
Use `bg-elevation-300` here

2024-11-16 02:34 UTC, cryptosalomao commented on src/components/ui/checkbox.tsx
> +      "disabled:!bg-[#D1CCC1] disabled:!border-0 disabled:cursor-not-allowed"
These comments are redundant. The data attributes already provide context about what style variation the properties belong to.

2024-11-16 02:37 UTC, cryptosalomao requested changes
Hi. Thanks for your contribution! Please review the points I've highlighted

2024-11-16 08:52 UTC, nafisreza commented
Fixed. Kindly check now.

2024-11-16 20:13 UTC, cryptosalomao approved these changes
Hi @nafisreza all looking good! Thanks for the contribution!

2024-11-18 12:24 UTC, mtbitcr approved these changes

2024-11-18 12:27 UTC, mtbitcr commented
LGTM.
@cryptosalomao you can merge it.
@nafisreza please provide your taproot Bitcoin address for awards. You get 500 e-IOU tokens.

2024-11-18 13:15 UTC, merged

2024-11-18 13:32 UTC, nafisreza commented
Thanks a ton @mtbitcr 
I have sent you a DM on Linkedin. Kindly check.

2024-11-20 15:36 UTC, mtbitcr commented
@nafisreza please don't use GitHub keywords to close issues automatically. Just link PR to issue