feat: primary button variants
BitcreditProtocol/E-Bill-frontend pull request #55
Opened 2024-11-15 19:09 UTC by nafisreza

fixes #51 

Changes:
- Added new variants: default and outlined with their respective states (default, hover, active, focused, disabled)
- New size variants with padding and font sizes according to figma design
- Added icon property to handle icon positioning (also icon-only)
- rounded variant for different border-radius options
- Added fullWidth variant (inherits from parent container)
- compound variants to handle icon-only padding for different sizes
- also kept previous variants for future use

Screenshots/Videos:

https://github.com/user-attachments/assets/64619452-8a42-458a-b0e4-596f72e68228

Acceptance criteria:
- [x] The component styling must match all the states specified in the design specs: default, hover, focused, active and disabled
- [x] The component must have two different sizes, as per the design specs: extra small (xs), small (sm), medium (md) and large (lg)
- [x] There has to be a property to set the button size (xs, sm, md or lg)
- [x] There has to be a property to turn the button into the disabled state
- [x]  The component must have a full width variant
- [x] The component must have a full rounded variant

2024-11-16 02:01 UTC, cryptosalomao commented on src/components/ui/button.tsx
> +        xs: "text-xs px-4 py-[10px]",
Use `py-2.5` here

2024-11-16 02:05 UTC, cryptosalomao commented on src/components/ui/button.tsx
> +        lg: "text-base px-8 py-5",
Use `py-[18px]` here

2024-11-16 02:06 UTC, cryptosalomao commented on src/components/ui/button.tsx
> +      },
Unnecessary variant. We can control icon positioning directly with class utilities.

2024-11-16 02:07 UTC, cryptosalomao commented on src/components/ui/button.tsx
> +      },
Redundant.

2024-11-16 02:07 UTC, cryptosalomao commented on src/components/ui/button.tsx
> +      }
We can use class utilities instead of this variant too, as it's redundant.

2024-11-16 02:24 UTC, cryptosalomao commented
Hello @nafisreza thank you for your contribution! Overall, it looks good, except to some points I've highlighted.

Also, the focused state does not work as intended. Please take a look on the video below:


https://github.com/user-attachments/assets/065d5935-8e43-46d0-87f3-2e3261410f98

The desired behavior is for the border to grow outside of the button area, and not to shrink it.

2024-11-16 02:40 UTC, cryptosalomao requested changes
Since we need shadcn, let's stick to its conventions. Please check the link below to have a base to address some of the comments I left:

https://ui.shadcn.com/docs/components/button

2024-11-16 02:40 UTC, cryptosalomao commented on src/components/ui/button.tsx
> +    const [_icon, text] = childrenArray;
Unnecessary as we don't need to manipulate the icon directly.

2024-11-16 02:40 UTC, cryptosalomao commented on src/components/ui/button.tsx
> +        {icon !== "icon-only" && text}
Unnecessary as we don't need to manipulate the icon directly.

2024-11-16 02:40 UTC, cryptosalomao commented on tailwind.config.js
> +          inactive: '#D1CCC1'
We have these variables elsewhere. Even though the naming may change in the future, reuse them.

2024-11-16 02:40 UTC, cryptosalomao commented on src/components/ui/button.tsx
> +        outlined: "border border-base text-base hover:border-divider-100 hover:text-divider-100 focus:border-[6px] focus:border-divider-75 active:border-base-active disabled:border-base-inactive disa
Unnecessary extra variant. Use existing outline instead.

2024-11-16 02:40 UTC, cryptosalomao commented on src/components/ui/button.tsx
> +          hover:"text-accent-foreground",
Attention to indentation here

2024-11-16 09:06 UTC, nafisreza commented on tailwind.config.js
> +          inactive: '#D1CCC1'
the default and inactive is available as text-300 and elevation-300, but hover & active color is not there.

2024-11-16 09:15 UTC, nafisreza commented
Ah, @cryptosalomao. I guess I got the intention wrong and overengineered a bit. 🙃 Kindly take a look now and let me know if anything else needs to be changed. 😃

2024-11-16 20:14 UTC, cryptosalomao approved these changes
All looking good! Thank you very much @nafisreza

2024-11-16 23:01 UTC, cryptosalomao requested changes
Hey @nafisreza, the issue with the border not growing outside of the content box is still there. Could you please review it?

2024-11-17 13:44 UTC, nafisreza commented
@cryptosalomao thanks for noticing it. I have added content-box to the focus state. Now it should work fine. Note that, if there is no space for the button (when the button takes whole width of the parent) in that case, it will still shrink it as it has no breathing space around it.
I am attaching a video for your reference.

https://github.com/user-attachments/assets/43298d25-2e1c-4fcc-858e-97a92f40d889

2024-11-19 12:28 UTC, mtbitcr commented
Hey, @nafisreza. Please, always link PR to task. Thanks!

2024-11-20 18:07 UTC, nafisreza reviewed
Changes reviewed.

2024-11-21 15:35 UTC, cryptosalomao commented
Hi @nafisreza we have a new button size in our design specs. Would you like to work on it?

Here's the link:
https://www.figma.com/design/JGS3SkgNhw9wE8sZGYNbvF/Nodes?node-id=121-5356&node-type=frame&t=ukiOvCVzC0fEagFT-0

2024-11-21 19:43 UTC, nafisreza commented
@cryptosalomao the new size has been added. Kindly check.

2024-11-22 11:25 UTC, cryptosalomao approved these changes
LGTM

2024-11-22 11:25 UTC, merged