Toast Component
BitcreditProtocol/E-Bill-frontend pull request #82
Opened 2024-11-20 18:02 UTC by nafisreza

closes #74 

### Changes:
- Supports 4 different variants (info, success, warning, and error)
- Can be positioned on different places of the screen (top-left, bottom-left, top-right, bottom-right)
- Size, colors, icons according to the Figma design. 

### How to use:
``` 
<Button
      onClick={() => {
        toast({
          title: "Alert message goes here!",
          description: "This is where a alert description goes, replace it here",
          variant: "success",
          position: "bottom-right",
          duration: 2000,
        })
      }}
    >
      Show Toast
</Button>
```

### Screenshots:

https://github.com/user-attachments/assets/8172cbbb-f96a-4072-871c-c8119d43f407

2024-11-20 18:14 UTC, nafisreza commented
One thing that can be further improved here is when the toast is positioned on the left, we can animate the closing in the same direction or it may be good as it is (whatever looks cool). Currently, it is using the translation x/y from radix-toast-swipe. Then the animation would need to be written manually.

2024-11-20 20:28 UTC, cryptosalomao commented on src/components/ui/toast.tsx
> +  })();
Here is a cleaner approach:

```typescript
const positionStyles = {
    'top-left': 'top-0 left-0',
    'top-right': 'top-0 right-0',
    'bottom-left': 'bottom-0 left-0',
    'bottom-right': 'bottom-0 right-0',
}[position] || 'top-0 right-0';
```

2024-11-20 20:29 UTC, cryptosalomao commented on src/components/ui/toast.tsx
> +        `fixed z-[100] flex max-h-screen w-full flex-col-reverse p-4 sm:flex-col md:max-w-[420px] ${positionStyles}`,
`z-10` is sufficient here

2024-11-20 20:31 UTC, cryptosalomao commented on src/components/ui/toast.tsx
> +      variant: "success",
`info` as a default variant

2024-11-20 20:31 UTC, cryptosalomao commented on src/components/ui/toast.tsx
> +    <X className="h-5 w-5 text-text-200" />
missing `strokeWidth` prop here, must be 1px thick

2024-11-20 20:32 UTC, nafisreza commented on src/components/ui/toast.tsx
> +        `fixed z-[100] flex max-h-screen w-full flex-col-reverse p-4 sm:flex-col md:max-w-[420px] ${positionStyles}`,
Right. Actually this value is from shadcn itself.

2024-11-20 20:32 UTC, cryptosalomao commented on src/components/ui/toast.tsx
> +    className={cn("text-[14px] text-text-200 font-[500]", className)}
`text-sm` and `font-medium` in this line

2024-11-20 20:38 UTC, cryptosalomao commented on src/components/ui/toaster.tsx
> +  }
Cleaner version:

```typescript
const icons = {
    success: <CircleCheckIcon className="w-4 h-4 text-signal-success" />,
    info: <InfoIcon className="w-4 h-4" />,
    warning: <TriangleAlertIcon className="w-4 h-4 text-signal-alert" />,
    error: <OctagonXIcon className="w-4 h-4 text-signal-error" />,
};

const icon = icons[variant] || icons.info;
```

And notice the `strokeWidth` and the icon dimensions too

2024-11-20 20:38 UTC, cryptosalomao commented on src/components/ui/toaster.tsx
> +      {toasts.map(function ({ id, title, description, action, variant, position, ...props }) {
`position` is unused here

2024-11-20 20:39 UTC, cryptosalomao commented on src/hooks/use-toast.ts
>  "use client";
This line can go away

2024-11-20 20:39 UTC, cryptosalomao commented on src/hooks/use-toast.ts
> +} as const
This has been already fixed. Please rebase main into your branch

2024-11-20 20:41 UTC, cryptosalomao commented on src/hooks/use-toast.ts
> +    }
keep the enum

2024-11-20 20:43 UTC, cryptosalomao requested changes
Hey @nafisreza very good one! Thanks for the contrib. I've left some important points to be addressed.

Please notice that a more recent version has been merged to `main` in order to fix some type warnings, so rebase `main` into your branch. And it's important to stick with the project's conventions for eslint, so please configure your IDE to not override them. Lots of semicolons have been removed unnecessarily.

2024-11-21 08:27 UTC, mtbitcr commented
@nafisreza we will announce PRs Rules soon. About PR naming, necessary fields to fill in and so on

2024-11-21 08:30 UTC, mtbitcr commented
@nafisreza I don't understand to what task this PR belong. Please stick to naming #TASKNUMBER_TASKNAME. And also attach task in Development.

2024-11-21 11:52 UTC, mtbitcr commented
Hey @nafisreza . Please re-request review after fixing comments.

2024-11-21 13:48 UTC, cryptosalomao approved these changes
LGTM

2024-11-21 13:48 UTC, merged